services:
  - type: web
    name: video-downloader-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
